services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /Users/manav.garg/Desktop/Personal/postgres:/var/lib/pgsql
